### ISSUE TITLE
syntax error, unexpected 'else' (T_ELSE)

### ISSUE THREAD

**Issue by MiuliKain** [Liupaperbox/Rorical#1]
![](https://raw.githubusercontent.com/MiuliKain/data/master/img/20200312113139.png)
套用这个主题后。
求解，谢谢作者大大！

**Comment by Liupaperbox** [comment]
抱歉，我在测试的时候没用遇到这个问题，可以详细描述一下嘛？

**Comment by MiuliKain** [comment]
详情：PHP版本大概为5.6（当时的环境因为某些原因没存下来
SQL版本10
Typecho没有其他插件

**Comment by Liupaperbox** [comment]
试试在在config.inc.php里加入
`define('__TYPECHO_DEBUG__', true);`
查看详细的错误

**Comment by mlt131220** [comment]
我也遇到了，显示如下
`syntax error, unexpected 'else' (T_ELSE)
ParseError: syntax error, unexpected 'else' (T_ELSE) in /wwwroot/usr/themes/Rorical/index.php:79
Stack trace:
#0 /wwwroot/var/Typecho/Router.php(138): Widget_Archive->render()
#1 /wwwroot/index.php(23): Typecho_Router::dispatch()
#2 {main}`

**Comment by DavidTai780** [comment]
```
<? if (count($this->tags)>0): ?> //T_ELSE错误源自于此---index.php 第70行改为<?php if(count).... 就可以运行了   
<i class="fa fa-tags"></i>     
<?php foreach( $this->tags as $tags): ?>  
<a href="<? print($tags['permalink']) ?>" class="badge badge-success"><? print($tags['name']) ?></a>   
<?php endforeach;?>   
<?php else: ?>	
<i class="fa fa-tags"></i> <a class="badge badge-default text-white">无标签..</a> 
 <?php endif;?>
```
